global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:4000']

  - job_name: 'inventory-service'
    static_configs:
      - targets: ['inventory-service:5000']

  - job_name: 'chat-service'
    static_configs:
      - targets: ['chat-service:6000']

  - job_name: 'cart-service'
    static_configs:
      - targets: ['cart-service:7000']
